export const posts = [
    {
        id: 1,
        title: 'Adjusting Visual Comfort Goodman Pendants',
        body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
        images: [
            'url1',
            'url2',
            'url3',
        ],
        publishedOn: '01/02/2022',
        author: {
            id: 1,
            name: 'Emma J',
        },
        category: 'Bathroom',
        tags: [
            'carpet',
            'couch',
        ],
        comments: [
            {
                text: 'gsdfagfsadfsadf',
                author: 'John K',
                authorId: 2,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 1,
            },
            {
                text: 'dfasfsdaf',
                author: 'John T',
                authorId: 3,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 1,
            },
            {
                text: 'gsfhdghdfgh',
                author: 'John R',
                authorId: 4,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 1,
            },
        ],
        likes: 20,
        saves: 30,
    },
    {
        id: 2,
        title: 'hello',
        body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
        images: [
            'url1',
            'url2',
            'url3',
        ],
        publishedOn: '01/02/2022',
        author: {
            id: 1,
            name: 'Emma J',
        },
        category: 'Bathroom',
        tags: [
            'carpet',
            'couch',
        ],
        comments: [
            {
                text: 'gsdfagfsadfsadf',
                author: 'John K',
                authorId: 2,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 2,
            },
            {
                text: 'dfasfsdaf',
                author: 'John T',
                authorId: 3,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 2,
            },
            {
                text: 'gsfhdghdfgh',
                author: 'John R',
                authorId: 4,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 3,
            },
        ],
        likes: 20,
        saves: 30,
    },
    {
        id: 3,
        title: 'hello',
        body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
        images: [
            'url1',
            'url2',
            'url3',
        ],
        publishedOn: '01/02/2022',
        author: {
            id: 1,
            name: 'Emma J',
        },
        category: 'Bathroom',
        tags: [
            'carpet',
            'couch',
        ],
        comments: [
            {
                text: 'gsdfagfsadfsadf',
                author: 'John K',
                authorId: 2,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 3,
            },
            {
                text: 'dfasfsdaf',
                author: 'John T',
                authorId: 3,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 3,
            },
            {
                text: 'gsfhdghdfgh',
                author: 'John R',
                authorId: 4,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 3,
            },
        ],
        likes: 20,
        saves: 30,
    },
    {
        id: 4,
        title: 'hello',
        body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
        images: [
            'url1',
            'url2',
            'url3',
        ],
        publishedOn: '01/02/2022',
        author: {
            id: 1,
            name: 'Emma J',
        },
        category: 'Bathroom',
        tags: [
            'carpet',
            'couch',
        ],
        comments: [
            {
                text: 'gsdfagfsadfsadf',
                author: 'John K',
                authorId: 2,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 4,
            },
            {
                text: 'dfasfsdaf',
                author: 'John T',
                authorId: 3,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 4,
            },
            {
                text: 'gsfhdghdfgh',
                author: 'John R',
                authorId: 4,
                likes: 12,
                saves: 10,
                publishedOn: '01/02/2022',
                onPost: 'hello',
                onPostId: 4,
            },
        ],
        likes: 20,
        saves: 30,
    },
];

export const users = [{
    id: 1,
    firstName: 'Ivan',
    lastName: 'Ivanov',
    email: 'odisfn@abv.bg',
    userName: 'IvanIvan',
    posts: [
        {
            id: 1,
            title: 'Adjusting Visual Comfort Goodman Pendants',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Ivan Ivanov',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 1,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 1,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 1,
                },
            ],
            likes: 20,
            saves: 30,
        },
        {
            id: 2,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Ivan Ivanov',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 2,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 2,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 3,
                },
            ],
            likes: 20,
            saves: 30,
        },
        {
            id: 3,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Ivan Ivanov',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 3,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 3,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 3,
                },
            ],
            likes: 20,
            saves: 30,
        },
        {
            id: 4,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Ivan Ivanov',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 4,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 4,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 4,
                },
            ],
            likes: 20,
            saves: 30,
        },
    ],
    comments: [
        {
            text: 'gsfhdghdfgh',
            author: 'Ivan Ivanov',
            authorId: 4,
            likes: 12,
            saves: 10,
            publishedOn: '01/02/2022',
            onPost: 'hello',
            onPostId: 4,
        },
        {
            text: 'gsfhdghdfgh',
            author: 'Ivan Ivanov',
            authorId: 4,
            likes: 12,
            saves: 10,
            publishedOn: '01/02/2022',
            onPost: 'hi hello',
            onPostId: 2,
        },
        {
            text: 'gsfhdghdfgh',
            author: 'Ivan Ivanov',
            authorId: 4,
            likes: 12,
            saves: 10,
            publishedOn: '01/02/2022',
            onPost: 'Adjusting Visual Comfort Goodman Pendants',
            onPostId: 1,
        },
    ],
},
{
    id: 2,
    firstName: 'Petkan',
    lastName: 'Petkanov',
    email: 'pefj@abv.bg',
    userName: 'PetkanPetkan',
    posts: [
        {
            id: 1,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Emma J',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello x2',
                    onPostId: 1,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 4,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hi hello',
                    onPostId: 2,
                },
            ],
            likes: 20,
            saves: 30,
        },
        {
            id: 2,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Emma J',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello x2',
                    onPostId: 1,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 4,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hi hello',
                    onPostId: 2,
                },
            ],
            likes: 20,
            saves: 30,
        },
        {
            id: 3,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Emma J',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello x2',
                    onPostId: 1,
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hello',
                    onPostId: 4,
                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                    onPost: 'hi hello',
                    onPostId: 2,
                },
            ],
            likes: 20,
            saves: 30,
        },
        {
            id: 4,
            title: 'hello',
            body: 'fsdjkhfjklshafdlkhsakdjlfhkljsdafh',
            images: [
                'url1',
                'url2',
                'url3',
            ],
            publishedOn: '01/02/2022',
            author: {
                id: 1,
                name: 'Emma J',
            },
            category: 'Bathroom',
            tags: [
                'carpet',
                'couch',
            ],
            comments: [
                {
                    text: 'gsdfagfsadfsadf',
                    author: 'John K',
                    authorId: 2,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',
                },
                {
                    text: 'dfasfsdaf',
                    author: 'John T',
                    authorId: 3,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',

                },
                {
                    text: 'gsfhdghdfgh',
                    author: 'John R',
                    authorId: 4,
                    likes: 12,
                    saves: 10,
                    publishedOn: '01/02/2022',

                },
            ],
            likes: 20,
            saves: 30,
        },
    ],
    comments: [
        {
            text: 'gsfhdghdfgh',
            author: 'John R',
            authorId: 4,
            likes: 12,
            saves: 10,
            publishedOn: '01/02/2022',
        },
        {
            text: 'gsfhdghdfgh',
            author: 'John R',
            authorId: 4,
            likes: 12,
            saves: 10,
            publishedOn: '01/02/2022',
        },
        {
            text: 'gsfhdghdfgh',
            author: 'John R',
            authorId: 4,
            likes: 12,
            saves: 10,
            publishedOn: '01/02/2022',
        },
    ],
}];

export const categories = [
    'Bathrooms',
    'Building a Home',
    'Landscape Design',
    'Flooring',
    'Furniture',
    'Home Decorating',
    'Kitchens',
    'Living Room',
    'Paint',
    'DYI',
    'Windows',
    'Other',
];
